from __future__ import annotations

from fireflyframework_genai.exceptions import FireflyGenAIError


class DworkersError(FireflyGenAIError): ...


class WorkerError(DworkersError): ...


class WorkerNotFoundError(WorkerError): ...


class TenantError(DworkersError): ...


class TenantNotFoundError(TenantError): ...


class PlanError(DworkersError): ...


class PlanNotFoundError(PlanError): ...


class ConnectorError(DworkersError): ...


class ConnectorAuthError(ConnectorError): ...


class CheckpointError(DworkersError): ...


class CheckpointRejectedError(CheckpointError): ...


class KnowledgeError(DworkersError): ...


class VerticalError(DworkersError): ...


class VerticalNotFoundError(VerticalError): ...
