"""Presentation tool example — generate a strategy deck.

Demonstrates a two-phase workflow:
  1. An AnalystWorker generates strategic recommendations.
  2. The PowerPointTool turns those recommendations into a .pptx file.

The output file is saved as ``strategy_deck.pptx`` in the current directory.
"""

import asyncio
import os
import sys

if not os.environ.get("ANTHROPIC_API_KEY"):
    sys.exit("Error: set the ANTHROPIC_API_KEY environment variable first.")

from firefly_dworkers.tenants.config import TenantConfig
from firefly_dworkers.tools.presentation.models import SlideSpec
from firefly_dworkers.tools.registry import tool_registry
from firefly_dworkers.workers.analyst import AnalystWorker

config = TenantConfig(
    id="demo",
    name="Demo Corp",
    models={"default": "anthropic:claude-sonnet-4-5-20250929"},
    branding={"company_name": "Demo Corp"},
)


async def main() -> None:
    # Phase 1 — generate content with the AnalystWorker
    worker = AnalystWorker(config)
    result = await worker.run(
        "Produce exactly 4 bullet points summarizing a strategy for "
        "a consulting firm entering the AI advisory market. "
        "Keep each bullet under 20 words. Return ONLY the bullet "
        "points, one per line, no numbering."
    )
    bullets = [
        line.strip().lstrip("•-– ")
        for line in result.output.strip().splitlines()
        if line.strip()
    ]
    # Keep first 4 bullets
    bullets = bullets[:4]
    print("Generated strategy bullets:")
    for b in bullets:
        print(f"  • {b}")

    # Phase 2 — build the .pptx with the PowerPointTool
    ppt = tool_registry.create("powerpoint")
    slides = [
        SlideSpec(
            layout="Title Slide",
            title="AI Advisory Market Entry Strategy",
            content="Demo Corp — Strategic Recommendations",
            speaker_notes="Generated by Firefly Digital Workers.",
        ),
        SlideSpec(
            layout="Title and Content",
            title="Strategic Recommendations",
            bullet_points=bullets,
            speaker_notes="Key strategy pillars for market entry.",
        ),
    ]
    out_path = await ppt.create_and_save("strategy_deck.pptx", slides=slides)
    print(f"\nPresentation saved to {out_path}")


asyncio.run(main())
