"""Presentation tool example — generate a strategy deck with rich styling.

Demonstrates a two-phase workflow:
  1. An AnalystWorker generates strategic recommendations.
  2. The PowerPointTool turns those into a .pptx with charts, images, and styling.

The output file is saved as ``strategy_deck.pptx`` in the current directory.
"""

import asyncio
import os
import sys

if not os.environ.get("ANTHROPIC_API_KEY"):
    sys.exit("Error: set the ANTHROPIC_API_KEY environment variable first.")

from firefly_dworkers.design.models import TextStyle
from firefly_dworkers.tenants.config import TenantConfig
from firefly_dworkers.tools.presentation.models import ChartSpec, SlideSpec
from firefly_dworkers.tools.registry import tool_registry
from firefly_dworkers.workers.analyst import AnalystWorker

config = TenantConfig(
    id="demo",
    name="Demo Corp",
    models={"default": "anthropic:claude-sonnet-4-5-20250929"},
    branding={"company_name": "Demo Corp"},
)


async def main() -> None:
    # Phase 1 — generate content with the AnalystWorker
    worker = AnalystWorker(config)
    result = await worker.run(
        "Produce exactly 4 bullet points summarizing a strategy for "
        "a consulting firm entering the AI advisory market. "
        "Keep each bullet under 20 words. Return ONLY the bullet "
        "points, one per line, no numbering."
    )
    bullets = [
        line.strip().lstrip("•-– ")
        for line in result.output.strip().splitlines()
        if line.strip()
    ]
    bullets = bullets[:4]
    print("Generated strategy bullets:")
    for b in bullets:
        print(f"  • {b}")

    # Phase 2 — build the .pptx with enhanced styling
    ppt = tool_registry.create("powerpoint")

    title_style = TextStyle(font_name="Calibri", font_size=28, bold=True, color="#1a73e8")
    body_style = TextStyle(font_name="Calibri", font_size=14, color="#333333")

    slides = [
        SlideSpec(
            layout="Title Slide",
            title="AI Advisory Market Entry Strategy",
            content="Demo Corp — Strategic Recommendations",
            speaker_notes="Generated by Firefly Digital Workers.",
            title_style=title_style,
            body_style=body_style,
            background_color="#f8f9fa",
        ),
        SlideSpec(
            layout="Title and Content",
            title="Strategic Recommendations",
            bullet_points=bullets,
            speaker_notes="Key strategy pillars for market entry.",
            title_style=TextStyle(font_name="Calibri", font_size=24, bold=True, color="#1a73e8"),
            body_style=body_style,
        ),
        SlideSpec(
            layout="Title and Content",
            title="Market Opportunity",
            chart=ChartSpec(
                chart_type="bar",
                title="Projected Market Size ($B)",
                categories=["2024", "2025", "2026", "2027"],
                series=[{"name": "AI Advisory", "values": [12.5, 18.3, 27.1, 38.0]}],
            ),
            speaker_notes="Market sizing data from industry reports.",
        ),
    ]
    out_path = await ppt.create_and_save("strategy_deck.pptx", slides=slides)
    print(f"\nPresentation saved to {out_path}")


asyncio.run(main())
